version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      REPLICA: replica1
      KEEPER_ID: 1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
    ports:
      - '8123:8123'
      - '9000:9000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.59.0
    restart: on-failure
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '8025:8025'

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev

  # postgres:
  #   image: postgres:14.2-alpine
  #   restart: on-failure
  #   environment:
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #     POSTGRES_USER: uptrace
  #     POSTGRES_PASSWORD: uptrace
  #     POSTGRES_DB: uptrace
  #   volumes:
  #     - 'pg_data:/var/lib/postgresql/data/pgdata'
  #   ports:
  #     - '5432:5432'

volumes:
  ch_data:
    driver: local
  alertmanager_data:
    driver: local
  redislabs_data_1:
    driver: local
  redislabs_data_2:
    driver: local
  pg_data:
    driver: local
