version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  uptrace:
    #image: 'uptrace/uptrace:latest'
    image: 'uptrace/uptrace-dev:latest'
    volumes:
      - uptrace_data:/var/lib/uptrace
      - ./uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - '14317:14317'
      - '14318:14318'
    environment:
      - UPTRACE_DB_FILE=/var/lib/uptrace/uptrace.sqlite3
      #- DEBUG=2
    depends_on:
      clickhouse:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.59.0
    restart: on-failure
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ../../config/alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '8025:8025'

  redis1:
    image: redislabs/redis:6.2.18-42
    restart: on-failure
    volumes:
      - redislabs_data_1:/opt/redislabs
    ports:
      - '8443:8443'
      - '9443:9443'
      - '12000:12000'
      - '8070:8070'
    privileged: true

  redis2:
    image: redislabs/redis:6.2.18-42
    restart: on-failure
    volumes:
      - redislabs_data_2:/opt/redislabs
    ports:
      - '8444:8443'
      - '9444:9443'
      - '12001:12000'
      - '8071:8070'
    privileged: true

  redis-client:
    build:
      dockerfile: ./redis-client/Dockerfile
      context: .

volumes:
  uptrace_data:
    driver: local
  ch_data:
    driver: local
  alertmanager_data:
    driver: local
  redislabs_data_1:
    driver: local
  redislabs_data_2:
    driver: local
